// ============================================================
// Shared TypeScript types for XENO CRM
// ============================================================

// --- Enums ---
export type UserRole = 'ADMIN' | 'MARKETER';
export type Gender = 'MALE' | 'FEMALE' | 'OTHER';
export type HealthLabel = 'HIGHLY_LOYAL' | 'ACTIVE' | 'AT_RISK' | 'CHURN_RISK';
export type Channel = 'EMAIL' | 'SMS' | 'WHATSAPP' | 'PUSH';
export type CampaignStatus = 'DRAFT' | 'SCHEDULED' | 'RUNNING' | 'COMPLETED' | 'FAILED' | 'CANCELLED';
export type LogStatus = 'QUEUED' | 'SENT' | 'DELIVERED' | 'FAILED' | 'OPENED' | 'READ' | 'CLICKED' | 'CONVERTED';
export type EventType = 'QUEUED' | 'SENT' | 'DELIVERED' | 'FAILED' | 'OPENED' | 'READ' | 'CLICKED' | 'CONVERTED';
export type OrderStatus = 'PENDING' | 'PROCESSING' | 'SHIPPED' | 'DELIVERED' | 'CANCELLED' | 'RETURNED';
export type CartStatus = 'ACTIVE' | 'ABANDONED' | 'COMPLETED';

// --- Segment Filter Rules ---
export type FilterOperator = 'eq' | 'neq' | 'gt' | 'gte' | 'lt' | 'lte' | 'in' | 'not_in' | 'contains' | 'has';

export interface FilterRule {
  field: string;
  operator: FilterOperator;
  value: string | number | string[] | number[];
}

export interface FilterGroup {
  logic: 'AND' | 'OR' | 'NOT';
  rules: (FilterRule | FilterGroup)[];
}

// --- API Response Wrappers ---
export interface ApiResponse<T> {
  success: boolean;
  data: T;
  message?: string;
}

export interface PaginatedResponse<T> {
  success: boolean;
  data: T[];
  pagination: {
    total: number;
    page: number;
    pageSize: number;
    totalPages: number;
  };
}

export interface ApiError {
  success: false;
  error: string;
  code?: string;
  details?: unknown;
}

// --- User ---
export interface User {
  id: string;
  email: string;
  name: string;
  role: UserRole;
  createdAt: string;
}

export interface AuthResponse {
  token: string;
  user: User;
}

// --- Customer ---
export interface Customer {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  phone?: string;
  gender?: Gender;
  city?: string;
  state?: string;
  preferredCategory?: string;
  tags: string[];
  totalSpend: number;
  orderCount: number;
  avgOrderValue: number;
  lastOrderDate?: string;
  daysSinceLastOrder?: number;
  emailOpenRate: number;
  emailClickRate: number;
  healthScore: number;
  healthLabel: HealthLabel;
  createdAt: string;
  updatedAt: string;
}

// --- Order ---
export interface OrderItem {
  name: string;
  category: string;
  price: number;
  qty: number;
}

export interface Order {
  id: string;
  customerId: string;
  campaignId?: string;
  amount: number;
  status: OrderStatus;
  items: OrderItem[];
  createdAt: string;
  customer?: Pick<Customer, 'id' | 'firstName' | 'lastName' | 'email'>;
  campaign?: { id: string; name: string };
}

// --- Cart ---
export interface CartItem {
  name: string;
  category: string;
  price: number;
  qty: number;
}

export interface Cart {
  id: string;
  customerId: string;
  items: CartItem[];
  totalValue: number;
  status: CartStatus;
  lastActiveAt: string;
  createdAt: string;
  updatedAt: string;
  customer?: Pick<Customer, 'id' | 'firstName' | 'lastName' | 'email' | 'phone'>;
}

// --- Segment ---
export interface Segment {
  id: string;
  name: string;
  description?: string;
  filterRules: FilterGroup;
  customerCount: number;
  isAutoScheduled: boolean;
  autoObjective?: string;
  preferredChannel: Channel;
  lastComputedAt?: string;
  createdAt: string;
  updatedAt: string;
}

export interface SegmentPreview {
  count: number;
  sample: Pick<Customer, 'id' | 'firstName' | 'lastName' | 'email' | 'healthScore' | 'healthLabel'>[];
}

// --- Campaign ---
export interface CampaignVariant {
  id: string;
  campaignId: string;
  label: string;
  angle: string;
  subject?: string;
  body: string;
  targetProfile?: string;
}

export interface Campaign {
  id: string;
  name: string;
  description?: string;
  segmentId: string;
  channel: Channel;
  status: CampaignStatus;
  isAutoGenerated: boolean;
  scheduledAt?: string;
  launchedAt?: string;
  completedAt?: string;
  createdAt: string;
  segment?: Pick<Segment, 'id' | 'name' | 'customerCount'>;
  variants?: CampaignVariant[];
  stats?: CampaignStats;
}

export interface CampaignStats {
  total: number;
  queued: number;
  sent: number;
  delivered: number;
  failed: number;
  opened: number;
  clicked: number;
  converted: number;
  openRate: number;
  clickRate: number;
  conversionRate: number;
  deliveryRate: number;
}

// --- AI Types ---
export interface AISegmentResult {
  filterRules: FilterGroup;
  explanation: string;
  estimatedSize?: number;
}

export interface AICampaignVariant {
  label: string;
  angle: string;
  subject?: string;
  body: string;
  targetProfile: string;
}

export interface AIExplainability {
  recommendation: string;
  confidence: number;
  reasoning: string[];
  evidence: Record<string, unknown>;
  alternatives?: Array<{ segment: string; reason: string }>;
}

export interface AIAgentStep {
  step: string;
  status: 'pending' | 'running' | 'done' | 'error';
  message: string;
  data?: unknown;
}

export interface AIAgentResult {
  steps: AIAgentStep[];
  segmentId?: string;
  campaignDraft?: Omit<Campaign, 'id' | 'createdAt' | 'updatedAt'> & { variants: AICampaignVariant[] };
  explainability: AIExplainability;
}

export interface AIInsight {
  id: string;
  campaignId: string;
  summary: string;
  insights: string[];
  recommendations: string[];
  metrics: CampaignStats;
  createdAt: string;
}

// --- Analytics ---
export interface AnalyticsOverview {
  totalCustomers: number;
  activeCustomers: number;
  inactiveCustomers: number;
  churnRiskCustomers: number;
  totalCampaigns: number;
  activeCampaigns: number;
  avgOpenRate: number;
  avgClickRate: number;
  avgConversionRate: number;
  totalRevenue: number;
  revenueThisMonth: number;
}

export interface AnalyticsTrend {
  date: string;
  messagesSent: number;
  delivered: number;
  opened: number;
  clicked: number;
  converted: number;
  revenue: number;
}

export interface SegmentPerformance {
  segmentId: string;
  segmentName: string;
  campaigns: number;
  avgOpenRate: number;
  avgClickRate: number;
  avgConversionRate: number;
  totalRevenue: number;
}

// --- Marketing Memory ---
export interface MarketingMemory {
  id: string;
  campaignId?: string;
  segmentDescription: string;
  segmentCriteria: FilterGroup;
  channel: Channel;
  audienceSize: number;
  openRate: number;
  clickRate: number;
  conversionRate: number;
  revenueGenerated: number;
  performanceLabel?: string;
  notes?: string;
  createdAt: string;
}
